name: speckle_analyser
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.0-105.0.dev <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  dio: ^4.0.6
  flutter:
    sdk: flutter
  flutter_svg: ^1.0.3
  flutter_svg_provider: ^1.0.3
  get: ^4.6.5
  google_fonts: ^3.0.1
  http: ^0.13.4
  image: ^3.1.3
  image_picker: ^0.8.5+3
  image_pixels: ^2.0.2
  image_size_getter: ^2.1.1
  matrix2d: ^1.0.2
  ml_linalg: ^13.10.0
  vector_math: ^2.1.2

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/images/splash.svg
    - assets/images/homenav.png
    - assets/images/undraw.svg
    - assets/images/seed.jpg
    - assets/images/flash.png
