name: speckle_analyser
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.0-105.0.dev <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_svg: ^1.0.3
  flutter_svg_provider: ^1.0.3
  get: ^4.6.5
  google_fonts: ^3.0.1
  image_picker: ^0.8.5+3

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/images/splash.svg
    - assets/images/homenav.svg
    - assets/images/undraw.svg
    - assets/images/seed.jpg
